export const POINTS = {
  PORCH_DELIVERY: 250,
  MAILBOX_DELIVERY: 500,
  SHAMBLER_KILL: 10,
  RUNNER_KILL: 25,
  SPITTER_KILL: 40,
  PERFECT_DAY_BONUS: 1000,
  REMAINING_LIFE_BONUS: 5000,
  TRAINING_TARGET: 50,
  TRAINING_RAMP: 100,
  NONSUB_WINDOW: 25,
  NONSUB_TOMBSTONE: 15,
} as const;

export const GAME = {
  STARTING_LIVES: 3,
  TOTAL_HOUSES: 20,
  STARTING_SUBSCRIBERS: 10,
  MAX_SUBSCRIBERS: 10,
  TOTAL_DAYS: 7,
  STARTING_PAPERS: 15,
  STARTING_AMMO: 10,
} as const;

export const NEWSPAPER = {
  BASE_THROW_SPEED: 8,
  SUNDAY_SPEED_MULTIPLIER: 0.6,
  STUN_DAMAGE: 1,
  STUN_DURATION: 500,
} as const;

export const ZOMBIE_HP = {
  SHAMBLER: 2,
  RUNNER: 4,
  SPITTER: 4,
} as const;

export const ZOMBIE_SPEED = {
  SHAMBLER: 2.5,
  RUNNER: 7,
  SPITTER: 2.5,
} as const;

export const ZOMBIE_DAMAGE = {
  SHAMBLER: 1,
  RUNNER: 2,
  SPITTER: 2,
} as const;

export const HAZARD = {
  ICE_SLIDE_DURATION: 1500,
  LOG_WIDTH_PERCENT: 0.6,
  SPITTER_PUDDLE_DURATION: 3000,
} as const;

export const CITIZEN_PENALTY = {
  FRIENDLY_NEIGHBOR: -50,
  PANICKED_RUNNER: -100,
  ARMED_SURVIVALIST: -25,
} as const;

export const HOUSE_DAMAGE_POINTS = {
  RANCH_WINDOW: 2,
  RANCH_GNOME: 1,
  RANCH_FENCE: 1,
  COLONIAL_UPPER_WINDOW: 3,
  COLONIAL_LOWER_WINDOW: 2,
  COLONIAL_PORCH_FURNITURE: 1,
  VICTORIAN_STAINED_GLASS: 5,
  VICTORIAN_TOMBSTONE: 2,
  VICTORIAN_PORCH_RAILING: 1,
} as const;
